export default function Head() {
    return (
      <>
        <title>Tyler Alexander</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by ♡, green tea, and time." />
        <link
          rel="icon"
          href="/icon?<generated>"
          type="image/png"
          sizes="32x32"
        />
      </>
    )
  }
  